version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
